### ISSUE TITLE
Installing Dependencies with manylinux

### ISSUE THREAD

**Issue by colin99d** [PyO3/maturin-action#117]
Is there any way to add an argument like `install` for manylinux? I need to install [some packages](https://github.com/tauri-apps/wry/blob/dev/.github/workflows/build.yml#L30-L32) for wry to work properly.

**Comment by messense** [comment]
No way at the moment, just `apt install` won't be manylinux compatible when cross compiling because the host glibc version is too high.

**Comment by messense** [comment]
If you don't care about very old systems, you can only support glibc 2.31+ by using Ubuntu 20.04 GitHub Actions runner and build on the host instead of containers.

**Comment by colin99d** [comment]
Thanks!
