### ISSUE TITLE
Passing custom environment variables to Docker

### ISSUE THREAD

**Issue by jaychia** [PyO3/maturin-action#134]
Hi! 

I am trying to ensure that a custom environment variable that I use at build-time is passed into manylinux builds, but it seems we currently only corner-case certain env var prefixes such as `CARGO_*` and `RUST*`.

My use-case here is to create a Rust `const` that is dependent on environment variables at compilation-time.

My workaround is currently to add a `RUST*` prefix to my environment variable to circumvent this: https://github.com/Eventual-Inc/Daft/pull/432

However, it would be useful if maturin-action supported the specification of environment variables that are to be passed into the docker container at build-time!

A previous issue that was filed for this same request: #69

**Comment by messense** [comment]
Added `docker-options` option in #135, please try

```yaml
docker-options: -e ENV_VAR_NAME
```

or 

```yaml
docker-options: -e ENV_VAR_NAME=value
```
