### ISSUE TITLE
'target' option is ignored if `args` contains `--`

### ISSUE THREAD

**Issue by Smertig** [PyO3/maturin-action#139]
I'm using maturin-action in the following way:
```
- uses: PyO3/maturin-action@v1.35.0
  with:
    maturin-version: 'v0.13.7'
    target: x86
    command: publish
    args: "-- -Ctarget-feature=+crt-static"
```

My build fails with the output:
```
  --- stderr
  error: your Rust target architecture (64-bit) does not match your python interpreter (32-bit)
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit code: 101": `"cargo" "rustc" "--release" "--message-format" "json" "--lib" "--crate-type" "cdylib" "--" "-Ctarget-feature=+crt-static" "--target" "i686-pc-windows-msvc"`
```

I think the reason is that maturin is being called in this way:
```
maturin.exe publish -- -Ctarget-feature=+crt-static --target i686-pc-windows-msvc
...
```

The `--target` option is ignored because it's specified **[after](https://github.com/PyO3/maturin-action/blob/5ed602b2625c8c3c6bab26e8b10c6199dc0d614f/src/index.ts#L775-L777)** all the arguments that may contain `--` delimiter. When I changed my config to this one:
```
- uses: PyO3/maturin-action@v1.35.0
  with:
    maturin-version: 'v0.13.7'
    command: publish
    args: "--target i686-pc-windows-msvc -- -Ctarget-feature=+crt-static"
```
I've got what I expected:
```
maturin.exe publish --target i686-pc-windows-msvc -- -Ctarget-feature=+crt-static
...
```

**Comment by messense** [comment]
Interesting, thanks for the report! I think change from `Array.push` to `Array.unshift` should fix it: https://github.com/PyO3/maturin-action/pull/140.

**Comment by messense** [comment]
Please try `v1.35.2`.

**Comment by Smertig** [comment]
It works like a charm! Thank you for such a great support.
