### ISSUE TITLE
Can leak credentials

### ISSUE THREAD

**Issue by clbarnes** [PyO3/maturin-action#193]
Using maturin-action to upload wheels to PyPI using config like `args: -u __token__ -p ${{ secrets.MATURIN_PASSWORD }}` leaks those credentials onto PyPI, because the command is written to a script `run-maturin-action.sh` which then ends up in the deployed tarball. My PyPI token was just invalidated because it showed up on a pypi mirror, for example.

This can be worked around by using an environment variable instead of a command line argument to pass the token, but I wasn't expecting that script to be written and uploaded to PyPI. This should at least be documented clearly, or a check should be done to make sure the `-p` argument isn't passed.

**Comment by messense** [comment]
You should set token as env var instead of passing it via `-p`.

And maturin already supports trusted publisher so I'd recommend use that instead, see

* https://github.com/PyO3/maturin/pull/1603/files
* https://docs.pypi.org/trusted-publishers/using-a-publisher/

**Comment by clbarnes** [comment]
Thanks for the quick response!
