### ISSUE TITLE
Compile failed on aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by ariesdevil** [PyO3/maturin-action#197]
I use a rust c-binding crate called [croaring](https://github.com/RoaringBitmap/croaring-rs) in our project, we use maturin-action to generate python-binding in ci.

It's failed to compile on aarch64-unknown-linux-gnu, but it can be successfully compiled in aarch64 linux machine.

The failed log is here: https://github.com/datafuselabs/databend/actions/runs/5572307261/jobs/10178194633?pr=12011

The successes build on my local aarch64 linux:
![image](https://github.com/PyO3/maturin-action/assets/7812909/dd6007cf-7902-4389-ae32-ec88fe8d7cd3)

**Comment by messense** [comment]
The GCC version is very old for manylinux compatibility, unless someone port a devtoolset gcc **cross compiler** from CentOS/RHEL, you can only fix it by compiling on native or QEMU-emulated aarch64 Linux environment.

**Comment by messense** [comment]
But you can bump your manylinux version to `manylinux_2_28`, it should have a newer gcc which might work. 

Keep in mind that `manylinux_2_28` doesn't not support CentOS 7.
