### ISSUE TITLE
PyPI rejects package published from default CI.yml with `unsupported platform tag` errors

### ISSUE THREAD

**Issue by etjones** [PyO3/maturin-action#210]
Using Maturin v1.2.3 and a stock `CI.yml` created by `maturin new`, my project builds successfully for all platform/architecture targets. But trying to publish all the compiled wheels to PyPI yields the following messages for at least a couple Linux architectures:

`400 Binary wheel 'vtracer-0.6.5-cp310-cp310-linux_i686.whl' has an unsupported platform tag 'linux_i686'.`

Failures so far included `linux_i686` and `linux_aarch64`. 

I think it might be possible that PyPI would accept these wheels if they were labeled `manylinux2014_i686` and `manylinux2014_aarch64`, but I'm not sure how to change the CI.yml to generate those wheels.

Plus, if the default `CI.yml` is failing for me, maybe it's stopping some other projects from publishing too.

Here's an example Github Action run:  https://github.com/etjones/vtracer/actions/runs/6124812960/job/16625644076

**Comment by messense** [comment]
https://github.com/etjones/vtracer/blob/06f52dc3859b76a608858f5b05d338b4837a21fa/cmdapp/pyproject.toml#L27

You have disabled manylinux compatibility in `pyproject.toml`.

**Comment by etjones** [comment]
Thanks so much! That did the trick
