### ISSUE TITLE
Wrong version of maturin installed

### ISSUE THREAD

**Issue by messense** [PyO3/maturin-action#212]
See this PR, where I remove the version passed to `maturin-action` and pin the maturin version in `pyproject.toml`:
https://github.com/stinodego/polars/pull/84

Check the `release` workflow, which has a step "Build wheel". You can see under the "Install maturin" step that version `1.2.3` was installed:
https://github.com/stinodego/polars/actions/runs/6378845249/job/17310201145?pr=84

...even though `maturin` is pinned to `1.2.1` in `pyproject.toml`.

> maturin-action should install the constrained version by default: [PyO3/maturin-action#46](https://github.com/PyO3/maturin-action/pull/46)

If I look through this code, I would expect to see some logging from the `findVersion` function but I don't see anything 🤔

_Originally posted by @stinodego in https://github.com/PyO3/maturin/issues/1792#issuecomment-1742762331_

**Comment by messense** [comment]
Turns out nodejs `semver` library doesn't support `==1.2.1`, only `=1.2.1` is supported. 😂

**Comment by messense** [comment]
Published in `v1`, please give it a try.

**Comment by stinodego** [comment]
> Published in `v1`, please give it a try.

@messense I re-ran my example and now it correctly installs v1.2.1! Thanks for the fix 👌
