### ISSUE TITLE
`ring` crate at 0.17 fails to build under manylinux: auto

### ISSUE THREAD

**Issue by chrisdickinson** [PyO3/maturin-action#222]
Hey! Thanks for this action (& for maturin / pyo3 in general!) – they're great!

I'm dropping a line to let you know that projects that have a dependency on the `ring` crate at 0.17 or above fail to build on `manylinux: auto`. The author of the crate [mentioned](https://github.com/briansmith/ring/issues/1728) that it's impractical for that project to support sysroots older than GCC 4.8 itself, so they're not going to support older versions of manylinux.

There's a comment on that same issue that notes that `manylinux_2_28` is a viable target.

I'm primarily writing to increase awareness of the bug and the fix; please do close if this is an inappropriate issue tracker to raise the issue on. Thanks!

**Comment by messense** [comment]
Thanks, will pin this issue for a while.
