### ISSUE TITLE
Publishing failed on Windows

### ISSUE THREAD

**Issue by djc** [PyO3/maturin-action#224]
I am publishing releases from GitHub Actions using this action, but today it failed to find any interpreters on Windows:

https://github.com/instant-labs/instant-segment/actions/runs/6654425271

Any suggestions why that might be?

**Comment by messense** [comment]
Try upgrade maturin to latest version first

https://github.com/instant-labs/instant-segment/blob/e2771b776a49dc7b1faf5e35e322a3b19083de83/instant-segment-py/pyproject.toml#L2

`py.exe` on Windows did a breaking change in Python 3.11 which breaks old version of maturin, see https://github.com/PyO3/maturin/issues/1221.

**Comment by djc** [comment]
Okay, I've done this, but I'm running into other failures now. For example, while I would expect the `working-directory` argument to be relative to the checkout root, it seems to be relative to the current working dir?

I currently have https://github.com/instant-labs/instant-segment/pull/47 but this fails with pretty strange issues:

https://github.com/instant-labs/instant-segment/actions/runs/6800422246/job/18489112119

**Comment by messense** [comment]
Not sure what you mean, but the upload job doens't checkout the git repo so there is no `instant-segment-py` folder. I think you can simply remove `workding-directory` from upload job because `download-artifacts` action puts everything in `cwd` by default.

**Comment by djc** [comment]
Okay, I finally managed to straighten out all the issues. Thanks for the support.
