### ISSUE TITLE
Support for `working-directory`

### ISSUE THREAD

**Issue by daemontus** [PyO3/maturin-action#23]
Hello, and merry Christmas!

Maybe I am missing something, but is there a way to run this action in some sub-folder of the repository?

I am trying to have a Rust library and its Python bindings in the same repository, but keep the bindings as a separate project (i.e. something like a `bindings-py` sub-directory that is technically independent of the main Rust library).

However, no matter what I do, the action always seems to run in the repository root.

If this is not possible yet, how hard would it be to implement?

**Comment by messense** [comment]
See https://github.com/messense/maturin-action/issues/11#issuecomment-926621021

**Comment by messense** [comment]
BTW, GitHub Actions has [native support for `working-directory`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun) but I haven't tested it with this action yet.

> Using the working-directory keyword, you can specify the working directory of where to run the command.
>
> ```yaml
> - name: Clean temp directory
>  run: rm -rf *
>  working-directory: ./temp
> ```

**Comment by daemontus** [comment]
> BTW, GitHub Actions have [native support for `working-directory`](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsrun) but I haven't tested it with this action yet.
> 
> > Using the `working-directory` keyword, you can specify the working directory of where to run the command.
> > ```yaml
> > - name: Clean temp directory
> >   run: rm -rf *
> >   working-directory: ./temp
> > ```

This does not work here unfortunately (I've tested it in my repository). However, the workaround through `-m` you posted seems to resolve my issues (as long as you also properly configure other paths, but this was the one I had most problems with :)).

**Comment by messense** [comment]
Upstream issue: https://github.com/actions/runner/issues/467#issuecomment-624777265

**Comment by kddejong** [comment]
If you have to update `[tool.maturin]` in `pyproject.toml` as well to account for the full path if you are working in rust/python mixed project. https://github.com/PyO3/maturin#mixed-rustpython-projects

```
[tool.maturin]
python-source = "folder/to/python/"
```
