### ISSUE TITLE
Python interpreter `3.12` doesn't exist

### ISSUE THREAD

**Issue by LaihoE** [PyO3/maturin-action#230]
I've been happily using this action for some time. Been building python versions 3.7 - 3.11 and would of liked to add 3.12. I thought it was just not supported, but I managed to build it on windows so got curious. workflow: https://github.com/LaihoE/demoparser/actions/runs/6907154000/job/18793724229

On linux/mac im getting: 
```
💥 maturin failed
  Caused by: The given list of python interpreters is invalid
  Caused by: Python interpreter `3.12` doesn't exist
```

workflow: https://github.com/LaihoE/demoparser/blob/main/.github/workflows/deploy.yml

**Comment by messense** [comment]
Upgrade your maturin version.

https://github.com/LaihoE/demoparser/blob/b73d5a5abf815a9c7cf91cd66b978883b4f4b66a/src/python/pyproject.toml#L2

**Comment by LaihoE** [comment]
Thank you!
