### ISSUE TITLE
How to build for a crate not at the project root.

### ISSUE THREAD

**Issue by spacey-sooty** [PyO3/maturin-action#236]
I am trying to use this to create CI for a crate not at the root of the github repository. This is causing the build to fail as there is no Cargo.toml at the root of the project. I have tried passing a working directory into the github job but this doesn't affect this action causing the build to still fail. Is there any way for me to do this?

**Comment by messense** [comment]
See #23, you need to pass `working-directory` to this action because the global `working-directory` only works for `run`.
