### ISSUE TITLE
actions/upload-artifact@v4

### ISSUE THREAD

**Issue by elasticdotventures** [PyO3/maturin-action#238]
Just a heads up that github actions upload-artifact@v4 does not allow multiple artifacts with the same name. 

I think @v3 is generated by `maturin generate-ci github` .. not sure how long that will continue to work, just posting this here for anybody who runs across the same issue. 

[the docs](https://github.com/actions/upload-artifact?tab=readme-ov-file)
relevant section is:

_

> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.

_

**Comment by messense** [comment]
See https://github.com/PyO3/maturin/pull/1886
