### ISSUE TITLE
Matruin doesn't install latest built package and instead defaults to downloading older version from pypi

### ISSUE THREAD

**Issue by baseplate-admin** [PyO3/maturin-action#263]
Discussed on :
* https://github.com/PyO3/pyo3/issues/4161#issuecomment-2095351784

Workflow Run :
* https://github.com/baseplate-admin/resvg-py/actions/runs/8966120658/workflow

Generated file by maturin:
* https://github.com/baseplate-admin/resvg-py/blob/64623551931dcee5550980b91895c5e6dd322a8e/.github/workflows/CI.yaml

**Comment by messense** [comment]
Duplicate of https://github.com/PyO3/maturin/issues/1971
