### ISSUE TITLE
`cffi` install fails on Windows 3.13

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin-action#275]
Seen in https://github.com/pydantic/pydantic-core/actions/runs/9647421992/job/26606165701?pr=1340#step:8:38

It seems that `cffi` isn't released to work with 3.13 on Windows yet. We have https://github.com/python-cffi/cffi/pull/34 which has fixed the root cause but that's only on `cffi` main.

What's the preferred route here? Maybe `cffi` install can be optional?

**Comment by messense** [comment]
Ignoring the installation failure for the moment: https://github.com/PyO3/maturin-action/commit/f61caa214c9839739a727618c8965ae7282c2aa3, hopefully it will release it new version with 3.13 support soon.
