### ISSUE TITLE
Allow users to install packages in the maturin docker where maturin executes

### ISSUE THREAD

**Issue by Dan-wanna-M** [PyO3/maturin-action#276]
It is possible that building users' package requires more packages that the default environment(for example, using `mimalloc` requires gcc 4.9+ while build-essential only provides gcc4.8). but currently there do not exist an easy way to do so.

**Comment by messense** [comment]
There is a `before-script-linux` option.

**Comment by messense** [comment]
> for example, using `mimalloc` requires gcc 4.9+ while build-essential only provides gcc4.8

Note that if you upgrade GCC it may result in wheels that require higher manylinux version, in such case  IMO specify [a newer maturin-action `manylinux` version](https://github.com/PyO3/maturin-action?tab=readme-ov-file#manylinux-docker-container) should be preferred.
