### ISSUE TITLE
Maturin generated CI not pushing binaries to PyPI

### ISSUE THREAD

**Issue by shner-elmo** [PyO3/maturin-action#279]
Hey, I have a project that uses PyO3, and I used the command `maturin generate-ci` to create the GH actions workflow.
It had worked in the past, but for some reason the last step of the workflow fails silently, there is no error message so I'm not sure what to do.

This is the workflow:
https://github.com/shner-elmo/flashtext2/actions/runs/9792664428/workflow

**Comment by haixuanTao** [comment]
Have you used a tag? 

See: https://github.com/shner-elmo/flashtext2/actions/runs/9792664428/workflow#L104

**Comment by messense** [comment]
You have modified the generated workflow: https://github.com/shner-elmo/flashtext2/commit/0f4e1db7176874af40bf9395ed6e753f8a1fca4d
