### ISSUE TITLE
redundant parts in universal build name

### ISSUE THREAD

**Issue by Andrej730** [PyO3/maturin-action#282]
Noticed an issue tfzpy builds - https://github.com/ringsaturn/tzfpy/issues/61 and it seems to be caused by maturin github action.

Here's  a description from the issue linked above:

> Hi! I've noticed that mac build on pypi "tzfpy-0.15.5-cp312-cp312-macosx_10_12_x86_64.macosx_11_0_arm64.macosx_10_12_universal2.whl" has redundant parts about _x86_64 and _arm64 architectures included in the name - when _universal2 by definition means that it has both those architectures.
> 
> pip itself is kind of clever about this and will automatically pick universal build if user requiested x86_64 or arm64 and only universal build is available, e.g. command below will work (quickfix-arm64 has only universal build too), so there shouldn't be a need to specify all architectures in the filename explicitly.
> 
> ```
> pip install quickfix-arm64 --platform macosx_11_5_arm64 --python-version 3.9 --implementation cp --only-binary=:all: --target=./site-packages
> ```
>

**Comment by messense** [comment]
This is intentional so that old versions of pip that does not recognize `universal2` can still install it.
