### ISSUE TITLE
Build on x86 fails with missing library

### ISSUE THREAD

**Issue by FlareFlo** [PyO3/maturin-action#283]
Building in Github CI fails with `/root/.rustup/toolchains/nightly-i686-unknown-linux-gnu/bin/cargo: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`
An example workflow of mine is linked [here](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/actions/runs/10321002590/job/28572852583).
Omitting [these targets](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/commit/d19fd4935d9528d90d7be5a8f93b6a1ea7ecb00f) (arbitrarily) resolved the issue.
[The failing workflow file with command used.](https://github.com/Warthunder-Open-Source-Foundation/wt_blk/blob/b2c9247f8cf4044e22e647f9d7fc965b0b0716a8/.github/workflows/pybindings_release.yml)

**Comment by messense** [comment]
Seems like a regression in cargo, please report to cargo instead.

See https://github.com/rust-lang/cargo/issues/13546

**Comment by FlareFlo** [comment]
Thanks! I will follow along with said issue then
