### ISSUE TITLE
Python 3.13t support

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/maturin-action#300]
Now that PyO3 0.23 is released, I think users will increasingly be trying to build for freethreaded Python.

What's the correct approach to do this? I have been working on this in https://github.com/pydantic/jiter/pull/165, I can get it to work but only by:
- sending the path output `setup-python` instead of an interpreter version, because `3.13t` is not recognised by `maturin` (I think)
- on manylinux images, manually working out where to look inside the image

It would be nice if setting `--interpreter 3.13t` as a maturin flag just did the right thing, or maybe there's another similar easy way.

It's more complicated in `jiter` and `pydantic-core` because we use PGO optimization so have quite a fiddly build 🙈

**Comment by messense** [comment]
See https://github.com/PyO3/maturin/pull/2310 which add `-i python3.13t` support, I haven't invest much time in it due to lacking 3.13t support in `setup-python` makes it hard to test it.

**Comment by davidhewitt** [comment]
Thanks, commented with a suggestion on that issue 👍
