### ISSUE TITLE
Rust cache with maturin-action

### ISSUE THREAD

**Issue by kevinheavey** [PyO3/maturin-action#53]
Is it possible to use a build cache with maturin-action? I would normally use https://github.com/Swatinem/rust-cache but it requires setting up a Rust toolchain first, which is something that gets handled inside maturin-action

**Comment by messense** [comment]
Tried and failed in https://github.com/messense/maturin-action/pull/43

**Comment by messense** [comment]
I'm going to close this because it's not easy to do cache with `Swatinem/rust-cache` for docker based builds.

I'll probably add [sccache](https://github.com/mozilla/sccache) with GitHub Actions cache support in the future.
